export interface AnimationEntry {
  slug: string;
  name: string;
  description: string;
  tags: string[];
  trigger: string;
  difficulty: "easy" | "medium" | "hard";
  cssRequired: boolean;
}

export const animations: AnimationEntry[] = [
  {
    slug: "3d-tilt",
    name: "3D Tilt Hero",
    description: "Images eparpillees autour d'un titre. Tout tilt en 3D au passage du curseur sur la section.",
    tags: ["hover", "3D", "JS", "hero", "parallax"],
    trigger: "Mouse move",
    difficulty: "medium",
    cssRequired: false,
  },
  {
    slug: "path-draw",
    name: "SVG Path Draw",
    description: "Un trait SVG se dessine progressivement quand la section entre dans le viewport.",
    tags: ["scroll", "SVG", "reveal", "graph"],
    trigger: "Scroll (IntersectionObserver)",
    difficulty: "easy",
    cssRequired: false,
  },
  {
    slug: "flow-lines",
    name: "Flow Lines",
    description: "Lignes SVG avec dash animees qui coulent vers un hub central. Style architecture technique.",
    tags: ["auto", "SVG", "dash", "workflow", "integration"],
    trigger: "Automatique (boucle)",
    difficulty: "medium",
    cssRequired: true,
  },
  {
    slug: "flow-circles",
    name: "Flow Circles",
    description: "Cercles colores qui voyagent le long de paths SVG. Variante dynamique des flow-lines.",
    tags: ["auto", "SVG", "animateMotion", "workflow"],
    trigger: "Automatique (boucle)",
    difficulty: "medium",
    cssRequired: true,
  },
  {
    slug: "s-curve-arrow",
    name: "S-Curve Arrow",
    description: "Fleche qui parcourt une courbe S smooth entre des etapes. Rotation automatique.",
    tags: ["auto", "SVG", "animateMotion", "timeline", "process"],
    trigger: "Automatique (boucle)",
    difficulty: "medium",
    cssRequired: false,
  },
  {
    slug: "border-spin",
    name: "Border Spin",
    description: "Bordure conic-gradient rotative revelee au hover. Effet premium sur les cards.",
    tags: ["hover", "CSS", "gradient", "card", "glow"],
    trigger: "Hover",
    difficulty: "easy",
    cssRequired: true,
  },
  {
    slug: "scroll-arcs",
    name: "Scroll Arcs",
    description: "Arcs concentriques SVG qui tournent en fonction du scroll. Style dashboard/monitoring.",
    tags: ["scroll", "SVG", "JS", "dashboard"],
    trigger: "Scroll (rAF)",
    difficulty: "hard",
    cssRequired: false,
  },
  {
    slug: "marquee",
    name: "Marquee",
    description: "Defilement horizontal infini de logos ou items. Boucle sans gap.",
    tags: ["auto", "CSS", "logos", "infinite"],
    trigger: "Automatique (boucle)",
    difficulty: "easy",
    cssRequired: true,
  },
  {
    slug: "char-spin",
    name: "Char Spin",
    description: "Chaque caractere apparait avec une rotation Y. Effet machine a ecrire premium.",
    tags: ["trigger", "CSS", "text", "reveal", "code"],
    trigger: "State change",
    difficulty: "easy",
    cssRequired: true,
  },
  {
    slug: "anti-grid-tabs",
    name: "Anti-Grid Tabs",
    description: "Tabs avec courbes concaves qui fusionnent visuellement avec le contenu. Technique mastra.ai.",
    tags: ["click", "CSS", "tabs", "SaaS", "advanced"],
    trigger: "Click",
    difficulty: "hard",
    cssRequired: false,
  },
  {
    slug: "eye-tracking",
    name: "Eye Tracking Tilt",
    description: "Cards avec yeux qui suivent le curseur + tilt 3D interactif. Effet immersif type hero section.",
    tags: ["hover", "JS", "3D", "hero", "interactive"],
    trigger: "Mouse move",
    difficulty: "hard",
    cssRequired: false,
  },
  {
    slug: "anti-grid-bento",
    name: "Anti-Grid Bento",
    description: "Bento grid 2D avec cartes connectees par bridges, courbes concaves clipPath aux jonctions, et border-radius selectif.",
    tags: ["CSS", "grid", "layout", "bento", "SaaS", "advanced"],
    trigger: "Static (layout)",
    difficulty: "hard",
    cssRequired: false,
  },
  {
    slug: "card-carousel",
    name: "Card Carousel Effects",
    description: "Carousel horizontal avec differents effets hover par card : fan spread, stack shift, 3D fade, colorize, camera pan.",
    tags: ["hover", "CSS", "carousel", "cards", "SaaS"],
    trigger: "Hover + Scroll",
    difficulty: "medium",
    cssRequired: false,
  },
  {
    slug: "staircase-clippath",
    name: "Staircase Chart ClipPath",
    description: "Graphe en escalier interactif — le curseur revele progressivement les lignes colorees via clipPath.",
    tags: ["hover", "SVG", "JS", "dashboard", "chart"],
    trigger: "Mouse move",
    difficulty: "medium",
    cssRequired: false,
  },
  {
    slug: "book-3d-tilt",
    name: "3D Book Tilt",
    description: "Couverture de livre qui tilt en 3D au mousemove avec une ombre dynamique qui suit le curseur.",
    tags: ["hover", "3D", "JS", "card", "product"],
    trigger: "Mouse move",
    difficulty: "medium",
    cssRequired: false,
  },
  {
    slug: "spotlight-card",
    name: "Spotlight Card",
    description: "Effet de lumiere radiale qui suit le curseur sur la card. Halo spotlight au hover.",
    tags: ["hover", "JS", "card", "glow", "premium"],
    trigger: "Mouse move",
    difficulty: "easy",
    cssRequired: false,
  },
  {
    slug: "magnetic-text",
    name: "Magnetic Text",
    description: "Chaque lettre reagit au curseur avec un changement de font-weight et un decalage magnetique.",
    tags: ["hover", "JS", "text", "interactive", "hero"],
    trigger: "Mouse move",
    difficulty: "medium",
    cssRequired: false,
  },
  {
    slug: "text-highlighter",
    name: "Text Highlighter",
    description: "Le texte se surligne progressivement au scroll — chaque mot passe de grise a blanc.",
    tags: ["scroll", "JS", "text", "reveal", "storytelling"],
    trigger: "Scroll",
    difficulty: "easy",
    cssRequired: false,
  },
  {
    slug: "fluid-tabs",
    name: "Fluid Navigation Tabs",
    description: "Un indicateur (underline ou pill) glisse fluidement vers le tab actif avec transition CSS.",
    tags: ["click", "CSS", "tabs", "navigation", "UI"],
    trigger: "Click",
    difficulty: "easy",
    cssRequired: false,
  },
  {
    slug: "sparkles",
    name: "Sparkles Particles",
    description: "Particules flottantes animees en pur CSS. Pas de canvas ni lib externe.",
    tags: ["auto", "CSS", "particles", "hero", "premium"],
    trigger: "Automatique (boucle)",
    difficulty: "easy",
    cssRequired: true,
  },
  {
    slug: "color-swapper",
    name: "Color Swapper on Scroll",
    description: "La couleur de fond change dynamiquement quand chaque section entre dans le viewport.",
    tags: ["scroll", "JS", "color", "transition", "landing"],
    trigger: "Scroll (IntersectionObserver)",
    difficulty: "medium",
    cssRequired: false,
  },
  {
    slug: "spotlight-tabs",
    name: "Spotlight Navigation Tabs",
    description: "Un fond lumineux (pill) glisse vers le tab actif avec un effet spotlight/glow.",
    tags: ["click", "hover", "CSS", "tabs", "glow"],
    trigger: "Click + Hover",
    difficulty: "medium",
    cssRequired: false,
  },
  {
    slug: "star-grid",
    name: "Star Grid",
    description: "Grille de points dont certains brillent aleatoirement avec une animation pulse.",
    tags: ["auto", "CSS", "grid", "background", "decoration"],
    trigger: "Automatique (aleatoire)",
    difficulty: "easy",
    cssRequired: false,
  },
  {
    slug: "globe-3d",
    name: "Interactive 3D Globe",
    description: "Globe 3D interactif avec markers et rotation auto. Canvas-based, drag-to-rotate.",
    tags: ["auto", "JS", "3D", "canvas", "interactive"],
    trigger: "Automatique + Drag",
    difficulty: "hard",
    cssRequired: false,
  },
  {
    slug: "accordion-details",
    name: "Animated Accordion",
    description: "Accordion anime avec expand/collapse smooth via grid-template-rows transition.",
    tags: ["click", "CSS", "accordion", "FAQ", "UI"],
    trigger: "Click",
    difficulty: "easy",
    cssRequired: false,
  },
  {
    slug: "text-reveal-scroll",
    name: "Text Reveal on Scroll",
    description: "Le texte apparait mot par mot au scroll avec un mask/clip progressif.",
    tags: ["scroll", "JS", "text", "reveal", "hero"],
    trigger: "Scroll",
    difficulty: "medium",
    cssRequired: false,
  },
  {
    slug: "motion-text",
    name: "Motion Text Scramble",
    description: "Le texte se debrouille — les caracteres se scramblent puis se fixent, ou glissent depuis le bas.",
    tags: ["trigger", "JS", "text", "scramble", "transition"],
    trigger: "State change",
    difficulty: "medium",
    cssRequired: false,
  },
  {
    slug: "sticky-scroll",
    name: "Sticky Scroll Sections",
    description: "Contenu sticky a gauche pendant que les cards a droite deroulent. Product tour style.",
    tags: ["scroll", "CSS", "sticky", "layout", "showcase"],
    trigger: "Scroll (position sticky)",
    difficulty: "medium",
    cssRequired: false,
  },
  {
    slug: "scroll-reveal",
    name: "Scroll Reveal",
    description: "Chaque element apparait avec un fade + slide au scroll. Wrapper utilitaire reutilisable.",
    tags: ["scroll", "JS", "reveal", "fade", "utility"],
    trigger: "Scroll (IntersectionObserver)",
    difficulty: "easy",
    cssRequired: false,
  },
  {
    slug: "vertical-tabs",
    name: "Vertical Navigation Tabs",
    description: "Tabs empiles verticalement avec un indicateur lateral anime.",
    tags: ["click", "CSS", "tabs", "sidebar", "navigation"],
    trigger: "Click",
    difficulty: "easy",
    cssRequired: false,
  },
  {
    slug: "spotlight-button",
    name: "Spotlight Button",
    description: "Bouton avec un halo lumineux qui suit le curseur sur hover. Effet premium.",
    tags: ["hover", "JS", "button", "glow", "CTA"],
    trigger: "Mouse move",
    difficulty: "easy",
    cssRequired: false,
  },
  {
    slug: "grid-pattern",
    name: "Grid Pattern Background",
    description: "Grille SVG repeatable avec effet de profondeur. Certaines cellules highlights.",
    tags: ["auto", "SVG", "background", "pattern", "decoration"],
    trigger: "Statique (decoration)",
    difficulty: "easy",
    cssRequired: false,
  },
  {
    slug: "dot-pattern",
    name: "Dot Pattern Background",
    description: "Grille de points SVG avec fade radial optionnel. Background subtil.",
    tags: ["auto", "SVG", "background", "pattern", "decoration"],
    trigger: "Statique (decoration)",
    difficulty: "easy",
    cssRequired: false,
  },
  {
    slug: "aurora-background",
    name: "Aurora Background",
    description: "Effet aurore boreale avec gradients multicouches animes lentement. Background premium.",
    tags: ["auto", "CSS", "background", "gradient", "premium"],
    trigger: "Automatique (boucle)",
    difficulty: "medium",
    cssRequired: false,
  },
  {
    slug: "meteors",
    name: "Meteors",
    description: "Pluie de meteores animes avec queue lumineuse. Ideal pour les hero backgrounds.",
    tags: ["auto", "CSS", "background", "particles", "hero"],
    trigger: "Automatique (boucle)",
    difficulty: "easy",
    cssRequired: false,
  },
  {
    slug: "flip-words",
    name: "Flip Words",
    description: "Mots qui se retournent et cyclent avec animation slide. Ideal pour les headlines dynamiques.",
    tags: ["auto", "JS", "text", "cycle", "hero"],
    trigger: "Automatique (boucle)",
    difficulty: "easy",
    cssRequired: false,
  },
  {
    slug: "typewriter",
    name: "Typewriter Effect",
    description: "Texte qui se tape caractere par caractere avec curseur clignotant. Efface et retape en boucle.",
    tags: ["auto", "JS", "text", "typing", "terminal"],
    trigger: "Automatique (boucle)",
    difficulty: "easy",
    cssRequired: false,
  },
  {
    slug: "number-ticker",
    name: "Number Ticker",
    description: "Compteurs animes qui grimpent de 0 a la valeur cible avec easing. Declenches au scroll.",
    tags: ["scroll", "JS", "counter", "stats", "dashboard"],
    trigger: "Scroll (IntersectionObserver)",
    difficulty: "easy",
    cssRequired: false,
  },
  {
    slug: "border-beam",
    name: "Border Beam",
    description: "Faisceau lumineux qui parcourt la bordure d'une card en boucle. Conic-gradient anime.",
    tags: ["auto", "CSS", "card", "glow", "premium"],
    trigger: "Automatique (boucle)",
    difficulty: "medium",
    cssRequired: false,
  },
  {
    slug: "wobble-card",
    name: "Wobble Card",
    description: "Card qui oscille subtilement au mousemove avec translation, scale et texture noise.",
    tags: ["hover", "JS", "card", "interactive", "3D"],
    trigger: "Mouse move",
    difficulty: "easy",
    cssRequired: false,
  },
  {
    slug: "morphing-text",
    name: "Morphing Text",
    description: "Texte qui morphe entre differents mots avec cross-fade blur. Transition fluide.",
    tags: ["auto", "CSS", "text", "transition", "hero"],
    trigger: "Automatique (boucle)",
    difficulty: "easy",
    cssRequired: false,
  },
  {
    slug: "confetti",
    name: "Confetti",
    description: "Explosion de confettis au clic. Particules avec physique (gravite, velocite, rotation).",
    tags: ["click", "JS", "particles", "celebration", "interactive"],
    trigger: "Click",
    difficulty: "medium",
    cssRequired: false,
  },
  {
    slug: "blob-cursor",
    name: "Blob Cursor",
    description: "Blob gradiante flou qui suit le curseur avec interpolation. Effet background interactif.",
    tags: ["hover", "JS", "cursor", "blob", "background"],
    trigger: "Mouse move",
    difficulty: "medium",
    cssRequired: false,
  },
  {
    slug: "text-pressure",
    name: "Text Pressure",
    description: "Lettres qui reagissent a la proximite du curseur : poids, taille et attraction magnetique.",
    tags: ["hover", "JS", "text", "interactive", "variable-font"],
    trigger: "Mouse move",
    difficulty: "medium",
    cssRequired: false,
  },
  {
    slug: "blur-text",
    name: "Blur Text Reveal",
    description: "Texte qui se revele en deblurrant caractere par caractere. Effet cinematique.",
    tags: ["scroll", "CSS", "text", "reveal", "blur"],
    trigger: "Scroll (IntersectionObserver)",
    difficulty: "easy",
    cssRequired: false,
  },
  {
    slug: "split-text",
    name: "Split Text",
    description: "Caracteres disperses qui s'assemblent a leur position correcte. Entree dynamique.",
    tags: ["scroll", "JS", "text", "reveal", "scatter"],
    trigger: "Scroll (IntersectionObserver)",
    difficulty: "medium",
    cssRequired: false,
  },
  {
    slug: "shiny-text",
    name: "Shiny Text",
    description: "Texte avec reflet brillant qui balaye en continu. Background-clip text + gradient anime.",
    tags: ["auto", "CSS", "text", "shimmer", "premium"],
    trigger: "Automatique (boucle)",
    difficulty: "easy",
    cssRequired: false,
  },
  {
    slug: "glitch-text",
    name: "Glitch Text",
    description: "Effet glitch digital avec offset RGB et decoupage clip-path. Style cyberpunk.",
    tags: ["auto", "CSS", "text", "glitch", "cyberpunk"],
    trigger: "Automatique (boucle)",
    difficulty: "medium",
    cssRequired: false,
  },
];

export function getAnimation(slug: string): AnimationEntry | undefined {
  return animations.find((a) => a.slug === slug);
}
